// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const browser: typeof import('wxt/browser')['browser']
  const createContentScriptIframe: typeof import('wxt/client')['createContentScriptIframe']
  const createContentScriptUi: typeof import('wxt/client')['createContentScriptUi']
  const defineBackground: typeof import('wxt/client')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/client')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
}
