name: Deploy Player to GitHub Pages

on:
  push:
    tags:
      - 'player-v*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.7.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies (no scripts)
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Build Player
        run: pnpm --filter @microdemo/player build
      - name: Add demo page
        run: |
          cp docs/demo.html apps/player/dist/demo.html
      - name: Create canonical filename
        run: |
          cp apps/player/dist/player.es.js apps/player/dist/player.js
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/player/dist
      - name: Upload dist artifact (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pages-dist
          path: apps/player/dist
          if-no-files-found: warn
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
