name: Release Player

on:
  push:
    tags:
      - 'player-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.7.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps (no scripts)
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build Player
        run: pnpm --filter @microdemo/player build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Player ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            apps/player/dist/*
          generate_release_notes: true
